### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by florajing** [hypertrons/hypertrons-crx#777] opened 2024-03-05 09:38 UTC
### Current Behavior

When using the hypercrx （installed on Edge）, I found that the visual graphs of fork and star are not displayed when I am not logged in.

### Expected Behavior

Hope it could be displayed even when not logged in.

### Environment

```markdown
- OS:
- Browser:
```

**Comment by tyn1998** [comment] 2024-03-05 10:00
Hi @florajing thanks for reporting the issue. it was reproduced when I signed out and had a try.

the issue is same as #775 and will be fixed ASAP.

**Comment by florajing** [comment] 2024-03-06 01:05
Thank you for your attention!
I just tried  and found that it still didn't show the visual graphs for fork and star when signed out.
Maybe it has something to do with Edge. Doesn't matter though, I'll just log in later if I need to.

**Comment by florajing** [comment] 2024-03-06 02:05
OK! Looking forward to~😊

**Closed** 2024-03-06 05:32 UTC
Labels: kind/bug
