### ISSUE TITLE
[Bug] Improvement needed for prettier on Windows

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#325] opened 2022-04-03 16:13 UTC
## Type of Issue
- [x] Bug
- [ ] Feature Request
- [ ] Performance issue
- [ ] Help Wanted
- [ ] Documention incomplete
- [x] Test Improvement
- [ ] Raise a Question

## Introduction to the issue
I am developing `hypercrx` on Windows operation and at the prettier format step, I encountered some problems:
1. Cannot execute `yarn run prettier`. The error message from the terminal is pasted below:
``` bash
$ prettier --write '**/*.{js,jsx,ts,tsx,json,css,scss}'
[error] No files matching the pattern were found: "'**/*.{js,jsx,ts,tsx,json,css,scss}'".
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
2. All the files that are included are prettier, even for those files that haven't been modified. I have tested it in a Linux environment and it turned out to be valid. So I guess it is because of the `eof``.

## Possible Fix
For problem1, I suggest that replacing `'` (single quote) with `\"`(double quote with escape character). It is tested valid on windows.

## Suggestion
Also, I wonder if we are considering adding the format checking into the PR test building phase to kind of reminding contributors to do the code prettier work.

**Comment by tyn1998** [comment] 2022-04-04 03:23
Thanks for firing the issue! I never run this project on Windows, so the problem is never exposed to me. I have tried your possilble solution and found it work on Mac so it might be the solution. Your suggestion on format integration is also great. Hopefully the feature will be integrated in our CI very soon!

**Closed** 2022-04-13 03:56 UTC
Labels: kind/bug
