### ISSUE TITLE
[Bug] Charts are not displayed when directly clicking into GitHub from email

### ISSUE THREAD

**Issue by Zzzzzhuzhiwei** [hypertrons/hypertrons-crx#702] opened 2023-07-05 11:55 UTC
### Version

1.9.0

### Current Behavior

When I received an email and directly clicked into GitHub from my email, it seemed like it wasn't working. It needs to be refreshed before it can return to normal. 
![image](https://github.com/hypertrons/hypertrons-crx/assets/115639837/055683ce-85f4-4c63-bc55-101843e349e9)
![image](https://github.com/hypertrons/hypertrons-crx/assets/115639837/92978e93-afe2-478e-93da-2d31ececbdde)

### Expected Behavior

![image](https://github.com/hypertrons/hypertrons-crx/assets/115639837/3d7481c9-bd39-485f-ab11-35806487255e)

### Environment

```markdown
- OS:Windows
- Browser:edge
```

**Comment by wxharry** [comment] 2023-07-05 19:39
@Zzzzzhuzhiwei Thanks for reporting! Are there any error messages in the inspect console?

**Comment by Zzzzzhuzhiwei** [comment] 2023-07-06 09:58
> @Zzzzzhuzhiwei Thanks for reporting! Are there any error messages in the inspect console?

Hi, these are messages in the console. In both cases, there will be no chart display.
![image](https://github.com/hypertrons/hypertrons-crx/assets/115639837/0caf71b4-689d-4cc1-8317-ad7b6da4f9f5)

![image](https://github.com/hypertrons/hypertrons-crx/assets/115639837/41de6f89-b581-4c00-8179-895eec1204f2)

**Comment by tyn1998** [comment] 2023-07-07 11:57
@Zzzzzhuzhiwei Thanks for reporting the issue!

But I cannot reproduce it on my machine 🤔 Hi @wxharry, did you reproduce the issue?

**Comment by andyhuang18** [comment] 2023-07-07 12:07
I also encountered such a problem. If you have not opened github before, open <a href='https://github.com/hypertrons/hypertrons-crx/issues/702#issuecomment-1623385842'>this webpage </a> for the first time, pull the page to the top, and several charts are not displayed.

**Comment by andyhuang18** [comment] 2023-07-07 12:09
I'll post the video later.

**Comment by andyhuang18** [comment] 2023-07-07 12:14
https://github.com/hypertrons/hypertrons-crx/assets/50283262/1ba4f6c4-b722-48b6-bc44-984169791242

**Comment by tyn1998** [comment] 2023-07-07 12:35
Maybe it is a Windows-specific issue.

I just quitted Chrome and did as you had done, but finding everything working well.

**Comment by wxharry** [comment] 2023-07-16 18:04
I cannot reproduce it either. Wired 🤔

**Comment by tyn1998** [comment] 2023-09-17 15:18
Hi @Zzzzzhuzhiwei, after v1.9.1 was released, does this issue still exist? Could you please check it again?

**Comment by Zzzzzhuzhiwei** [comment] 2023-09-18 03:03
> Hi @Zzzzzhuzhiwei, after v1.9.1 was released, does this issue still exist? Could you please check it again?

Hi,  I just checked it again, and this issue still exist.

**Comment by tyn1998** [comment] 2023-09-18 04:55
@Zzzzzhuzhiwei thank you. This issue remains open.

**Comment by tyn1998** [comment] 2024-03-06 04:15
Since the issue cannot be reliably reproduced and it doesn't cause big issue, let us close it :)

**Closed by tyn1998** 2024-03-06 04:15 UTC
Labels: kind/bug
