### ISSUE TITLE
[Bug] Perceptor tab missing icon when in Additional navigation options

### ISSUE THREAD

**Issue by wxharry** [hypertrons/hypertrons-crx#852] opened 2024-08-02 05:13 UTC
### Version

1.9.4

### Current Behavior

When window width is small, the perceptor tab goes to the additional navigation options. But an icon is missing for perceptor tab.

<img width="1035" alt="image" src="https://github.com/user-attachments/assets/34c06a81-ba46-4759-bfa3-8ecf2bfa7470">

### Expected Behavior

Perceptor tab should have the icon similar to other nav tabs.

### Environment

```markdown
- OS: not related
- Browser: not related
```

**Comment by dchobarkar** [comment] 2024-08-02 13:08
Hi there,

I would like to work on this issue. Could you please assign it to me?

Thank you!
Darshan

**Comment by dchobarkar** [comment] 2024-08-05 08:24
I have started working on this issue. I will update you with my progress soon.

Thank you,
Darshan

**Comment by HalloMelon** [comment] 2024-08-13 10:58
Hello @dchobarkar，how is the progress now😄 ~

**Comment by wangyantong2000** [comment] 2024-08-20 11:42
<img width="655" alt="image" src="https://github.com/user-attachments/assets/3c588d19-3c9c-407f-aad5-6a490cc387ec">
<img width="590" alt="image" src="https://github.com/user-attachments/assets/f496190d-f323-4bc9-99d7-23e83a4694a6">

The problem is that our current elements are different from the original ones.

**Comment by wangyantong2000** [comment] 2024-08-20 11:45
Due to the introduction of OSGraph in Perceptor, the Perceptor page will also be shown in the near future. This problem needs to be solved as soon as possible. Now it's up to me to solve this problem.

**Closed** 2024-08-21 05:03 UTC
Labels: good first issue, kind/bug
